config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'root#home'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all.order(created_at: :desc)
  	@post = Post.new
  end

  def create
  	post = Post.new(post_params)
  	if  post.save
  	    flash[:create] = 'Book was successfully created.'
  	    redirect_to post_path(post)
    else
    	render action: :new
    end
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	post = Post.find(params[:id])
  	if 	post.update(post_params)
  		flash[:update] = 'Book was successfully updated.'
  		redirect_to post_path(post)
	  else
    	render action: :new
    end
  end

  def destroy
  	post = Post.find(params[:id])
  	if  post.destroy
  	    flash[:destroy] = 'Book was successfully destroyed.'
  	    redirect_to posts_path
  	else
  		render action: :new
  	end
  end

  private
  def post_params
  	params.require(:post).permit(:title, :body) # require はPOSTで受け取る値のキーを設定、permit は許可するカラムを設定
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1> Editing Book</h1>

<%= form_for(@post) do |f| %>
	<h4> Title</h4>
	<%= f.text_field :title, class: 'book_title' %>

	<h4> Body</h4>
	<%= f.text_area :body, class: 'book_body' %>

	<p><%= f.submit 'Update Book' %></p>
<% end %>

<%= link_to "Show", post_path(@post), class: "show_#{@post.id}" %> |
<%= link_to "back", posts_path, class: "back" %>

app/views/posts/index.html.erb
<% if flash[:destroy] %>
  <p><%= flash[:destroy] %></p>
<% end %>

<h1> Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>body</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to "Show", post_path(post), class: "show_#{post.id}"%></td>
        <td><%= link_to "Edit", edit_post_path(post), class: "edit_#{post.id}" %></td>
        <td><%= link_to "Destroy", post_path(post), method: :delete, class: "destroy_#{post.id}", "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2> New book</h2>

<%= form_for(@post) do |f| %>

  <h4> Title</h4>
  <%= f.text_field :title, class: "book_title" %>

  <h4> Body</h4>
  <%= f.text_area :body, class: "book_body" %>

  <p><%= f.submit 'Create Book' %></p>

<% end %>

app/views/posts/show.html.erb
<% if flash[:create] %>
	<p><%= flash[:create] %></p>
<% elsif flash[:update] %>
	<p><%= flash[:update] %></p>
<% end %>


<h2> Title:</h2>
<p><%= @post.title %></p>
<h2> Body:</h2>
<p><%= @post.body %></p>

<%= link_to "edit", edit_post_path(@post), class: "edit_#{@post.id}"%> |
<%= link_to "back", posts_path, class: "back" %>

app/views/root/home.html.erb
<h1> ようこそBookersへ!</h1>

<p>Bookersでは、様々な書籍に関するあなたの意見や</p>
<br>
<p>印象を共有し交換することができます</p>
<br>
<%= link_to "start", posts_path %>